
title: cookieshake의 블로그


author:
  email: cookieshake@hotmail.com
  github: cookieshake

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

paginate: 5
highlighter: rouge
permalink: /posts/:title

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
